baseURL = 'http://Kh1ng.github.io/'
languageCode = 'en-us'
title = 'XeroLinux Podcast Feed'
theme = 'blist'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
paginate = 5

[languages.en.params]
  introTitle = "Welcome to the XeroLinux Podcast"
  introSubtitle = "XeroLinux news, discussions, and more."
  introPhoto = "/picture.jpg"
  logo = "images/Xero100.png"
[[languages.en.menu.main]]
    name = "Blog"
    url = "blog"
    weight = 1

[[languages.en.menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[languages.en.menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[languages.en.menu.main]]
    name = "Top Post"
    url = "/en/blog/emoji-support/"
    weight = 4
    
[params]
    darkModeToggle = true
    enableSearch = true

# [params.darkModeToggle]

[[menu.main]]
  name = "posts"
  url = "/post"

  frontBundle = "blog"

[params.homepage.social]
  # Global params common for all languages
#   title = "Follow me"
  twitter = "https://twitter.com/TechXero/"
#   linkedin = "https://linkedin.com/in/"
#   xing = "https://www.xing.com/profile/"
  github = "https://github.com/xerolinux/xero_iso"
#   medium = "https://medium.com/"
#   reddit = "https://reddit.com/"
#   dribbble = "https://dribbble.com/"
#   stackoverflow = "https://stackoverflow.com/"

# sectionPagesMenu = "menu"

# [params]
# noindex = true
# contentTypeName = "post"
# mainSections = ["post"]

# [params.about]
# title = "Episodes"
# description = "A podcast about [XeroLinux](XeroLinux.xyz)."
# logo = "images/Xero100.png"

# [[params.socialLinks]]
# icon = "fa-brands fa-github"
# title = "GitHub"
# url = "https://github.com/xerolinux/xero_iso"

# [menu]

#   [[menu.main]]
#     identifier = "post"
#     name = "Feed"
#     url = "/post/"
#     weight = 10