baseURL = 'http://Kh1ng.github.io/'
languageCode = 'en-us'
title = 'XeroLinux Podcast Feed'
theme = 'risotto'
DefaultContentLanguage = "en"
enableInlineShortcodes = true

sectionPagesMenu = "main"

[params]
noindex = false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
